### ISSUE TITLE
wrapInFunction is dependent upon wrapInEval

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/broccoli-concat#18]
I would expect `{ wrapInFunction: true, wrapInEval: false }` to transform
```js
// one.js
one();
// two.js
two();
```
into
```js
(function() {
one();
two();
})();
```
It's possible, though, that the correct answer is to create a `broccoli-iife` that wraps each of its inputs in an IIFE, then apply that *after* this concatenation with both `wrapInEval` and `wrapInFunction` turned off.

**Comment by stefanpenner** [comment]
this feature no longer exists
