### ISSUE TITLE
Files not matching inputFiles

### ISSUE THREAD

**Issue by brunovandamme** [ember-cli/broccoli-concat#29]
Just starting to play with Broccoli, but as I understand concat concatenates a set of matched files into a tree with just the one output file. Wouldn't it be more useful to return a tree still including all the files that were untouched by the concat operation? I just want the same tree back, but with the selected files concatenated. Or is there something I am missing?

**Comment by alanhogan** [comment]
You aren’t wrong per se but you can do this yourself by also using `concat` and `mergeTrees` to get back all the other files. (At least in theory!)

**Comment by stefanpenner** [comment]
> Wouldn't it be more useful to return a tree still including all the files that were untouched by the concat operation?

Im not apposed to this, just require
