### ISSUE TITLE
Make inputFiles parameter default to all files

### ISSUE THREAD

**Issue by roryokane** [ember-cli/broccoli-concat#36]
Currently, this is the simplest possible `concat` call in a `Brocfile.js`:

```javascript
var concat = require('broccoli-concat');

var appJs = concat('js', {
	inputFiles: ['**/*'],
	outputFile: '/all-js.js',
});
```

I think it would make sense for `inputFiles` to have the value `['**/*']` by default. That is, by default, `concat` concatenates all files in the given tree, in an arbitrary order. That would allow the plugin to be used like this:

```javascript
var appJs = concat('js', {
	outputFile: '/all-js.js',
});
```

Not requiring the `inputFiles` parameter would make it easier for people to get started using this plugin.

**Comment by stefanpenner** [comment]
Would accept a PR for this, should be easy to add:

* https://github.com/ember-cli/broccoli-concat/blob/master/concat.js#L18-L20
* https://github.com/ember-cli/broccoli-concat/blob/master/concat.js#L23
