### ISSUE TITLE
Don’t require ‘/’ at the start of outputFile path

### ISSUE THREAD

**Issue by roryokane** [ember-cli/broccoli-concat#37]
If I have this in my `Brocfile.js`:

```javascript
var concat = require('broccoli-concat');

var appJs = concat(sourceTree, {
	inputFiles: ['**'],
	outputFile: 'all-js.js',
});
```

Then I get the following error:

```
Error: Path must be absolute: "all-js.js"
```

I am forced to add a `/` to `outputFile`, like this:

```javascript
var appJs = concat(sourceTree, {
	inputFiles: ['**'],
	outputFile: '/all-js.js',
});
```

I don’t see why this should be necessary. If the caller doesn’t put a `/` at the front of the path, it is reasonable to assume that they mean the root directory of the output tree. What else would they mean?

This could be implemented by checking whether `outputFile` starts with `/`, and prepending `/` if it doesn’t, before doing anything else with that parameter.

**Comment by alanhogan** [comment]
+1

**Comment by alanhogan** [comment]
What was the resolution here?

**Comment by stefanpenner** [comment]
`outputFile` is merely joined with outputDir https://github.com/ember-cli/broccoli-concat/blob/master/concat.js#L73
