### ISSUE TITLE
add an exclude option

### ISSUE THREAD

**Issue by jrobeson** [ember-cli/broccoli-concat#40]
It'd be nice to be able to pass an entire glob for my input tree , but then exclude certain files like modernizr which can't often be used at the bottom of html body.

**Comment by ccoenen** [comment]
:+1: yes, that would be very helpful!

**Comment by kleichtle** [comment]
+1

**Comment by jedmao** [comment]
I would prefer the glob exclusion syntax for the inputFiles, like so:

```js
concat(scripts, {
  inputFiles: [
    'app/**/*.js',
    '!app/styles/**/*.js'
  ],
  outputFile: '/app.js'
});
```

**Comment by jedmao** [comment]
Perhaps you can use [glob-stream](https://www.npmjs.com/package/glob-stream) to achieve this goal?

**Comment by stefanpenner** [comment]
I would recommend users use `broccoli-funnel` on the input, to remove inputs files. Someday we may add this, but today this doesn't seem like a bug.
