### ISSUE TITLE
consider merge with broccoli-sourcemap-concat

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/broccoli-concat#43]
I have been working to update (and improve) https://github.com/ef4/broccoli-sourcemap-concat although I would also love to have the time to update this one. I unfortunately do not. Rather then having two contending libraries, (one falling behind recent improvements) let me suggestion merging efforts.

I will gladly add features missing to broccoli-sourcemap-concat, in hopes to unify the two worlds, and give users the best experience.

As for project name, I can go either way. broccoli-concat is likely the better name for the final project.

Anyways, let me know what you think.

**Comment by rlivsey** [comment]
:+1: completely agree.

I've not been using this myself recently (as ember-cli no longer uses it) and haven't had the time to keep up with the latest and greatest, so would gladly merge the two and hand-over the broccoli-concat name.

**Comment by stefanpenner** [comment]
Awesome. If you can add me as an admin here and owner on npm I can make the cutover this week.

**Comment by rlivsey** [comment]
I've added you to this repo & npm, not sure how to set as admin (or should I transfer ownership?)

**Comment by stefanpenner** [comment]
- [ ] transfer to a shared org
- [x] give @rlivsey and @ef4 commit
- [ ] begin merging broccoli-sourcemap-concat + broccoli-concat
