### ISSUE TITLE
Rebuild errors with changed footer files

### ISSUE THREAD

**Issue by adambullmer** [ember-cli/broccoli-concat#55]
consider the following file structure:
```
- app/
  |- app.js
  |- app.html
- Brocfile.js
```

`app/app.js`
```js
console.log('testing');
```

`app/app.html`
```html
<div>test</div>
```

`Brocfile.js`
```js
var concat = require('broccoli-concat');

module.exports = concat('app', {
    inputFiles  : [ '**/*.js' ],
    footerFiles : ['app.html'],
    outputFile  : 'scripts/app.js',
    annotation  : 'Concat: App'
});
```

While running a `broccoli serve`, the initial build returns the expected output:
`scripts/app.js`
```js
console.log('testing');
<div>test</div>
```

However, if I make a change to `app/app.html`, the file does not change. The console suggests a rebuild has happened, but this isn't generating a change in the concatinated file.

`Sample terminal output`
```
broccoli serve
Serving on http://localhost:4200


Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SourceMapConcat: Concat: App                  | 29ms                

Built - 32 ms @ Sat Apr 23 2016 13:37:43 GMT-0500 (CDT)

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SourceMapConcat: Concat: App                  | 2ms                 

Built - 4 ms @ Sat Apr 23 2016 13:38:00 GMT-0500 (CDT)
```

**Comment by stefanpenner** [comment]
good catch, will look into this.

**Comment by stefanpenner** [comment]
The solution is most likely to add a funnel for the header files and footerFiles to the inputNodes [here](https://github.com/ember-cli/broccoli-concat/blob/master/concat.js#L220)

**Comment by stefanpenner** [comment]
This should now be fixed by:

* for 3.x: https://github.com/ember-cli/broccoli-concat/pull/68
* for 2.x: https://github.com/ember-cli/broccoli-concat/pull/69
