### ISSUE TITLE
loader.js not included in ember-cli's vendor.js

### ISSUE THREAD

**Issue by alexBaizeau** [ember-cli/broccoli-concat#65]
I am not 100% sure why but since broccoli-concat got released my app refuses to boot.
![image](https://cloud.githubusercontent.com/assets/1521530/16849949/d3e71970-49ca-11e6-94ab-19728b0183d8.png)

Any suggestion on how to pin point what's going on?

**Comment by oparamo** [comment]
had the same issue and locking our version to 2.2.1 fixed it

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/broccoli-caching-writer/commit/9217adb369020a1fd0bd52b68445612c2fc1f62c

**Comment by alexBaizeau** [comment]
Thank You!!
