### ISSUE TITLE
This project appears to introduce 546 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/broccoli-concat#72]
own files that are likely included by mistake:
---

- [ ] test 44

dependencies (489)
----

 - [ ] broccoli-caching-writer     155 https://github.com/ember-cli/broccoli-caching-writer/issues/75
 - [ ] broccoli-kitchen-sink-helpers      50
 - [x] fast-sourcemap-concat     221 https://github.com/ef4/fast-sourcemap-concat/issues/23
 - [ ] lodash.merge       5
 - [ ] lodash.omit       5
 - [ ] lodash.uniq       5
 - [ ] mkdirp      45

**Comment by stefanpenner** [comment]
@mitchlloyd has offered to do this one

**Comment by mitchlloyd** [comment]
PR added to whitelist files in this project, now to recuse into dependencies...
